// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqnUZOYEQFFeyMex2SdXmz6sLS2FAdmY',
    appId: '1:441361950177:android:ae6345285c97996a755ea0',
    messagingSenderId: '441361950177',
    projectId: 'grammerchecker-a9837',
    storageBucket: 'grammerchecker-a9837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwml70I-FbBjW9HKhXlFQEFOtMmDBYHGM',
    appId: '1:441361950177:ios:a92427ab2bbd43df755ea0',
    messagingSenderId: '441361950177',
    projectId: 'grammerchecker-a9837',
    storageBucket: 'grammerchecker-a9837.appspot.com',
    iosBundleId: 'com.example.grammerCheckerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwml70I-FbBjW9HKhXlFQEFOtMmDBYHGM',
    appId: '1:441361950177:ios:a92427ab2bbd43df755ea0',
    messagingSenderId: '441361950177',
    projectId: 'grammerchecker-a9837',
    storageBucket: 'grammerchecker-a9837.appspot.com',
    iosBundleId: 'com.example.grammerCheckerApp',
  );
}
