import 'package:flutter/material.dart';

Color c = Color(0xff376AED);
const Color ObColor = Color.fromARGB(255, 54, 235, 174);
const Color mainClr = Color(0xff376AED);
const Color white = Colors.white;
const Color black = Colors.black;
const Color black54 = Colors.black54;
const Color heartclr = Color(0xffFF6262);
const Color red = Colors.red;
const Color pink = Colors.pink;
const Color purple = Colors.purple;
const Color deepPurple = Colors.deepPurple;
const Color indigo = Colors.indigo;
const Color blue = Color(0xff2F91EB);
const Color lightBlue = Colors.lightBlue;
const Color cyan = Colors.cyan;
const Color teal = Colors.teal;
const Color green = Colors.green;
const Color lightGreen = Colors.lightGreen;
const Color lime = Colors.lime;
const Color yellow = Colors.yellow;
const Color amber = Colors.amber;
const Color orange = Colors.orange;
const Color deepOrange = Colors.deepOrange;
const Color brown = Colors.brown;
const Color grey = Colors.grey;
const Color blueGrey = Colors.blueGrey;
